language: ruby
sudo: false
before_install:
- gem install bundler -v '< 2'
cache: bundler
rvm:
- '2.3.0'
- '2.3.1'
- '2.4.0'
- '2.4.1'
- '2.4.2'
- ruby-head
script:
- bundle
- bundle exec rake test rubocop
matrix:
  allow_failures:
  - rvm: ruby-head
notifications:
  slack:
    secure: bsPzMlTJZRJEvt16O8RdP/YeXA/TwbdPiGlRgNJXPn1vL4WU/uNBLBAG8JqCybLLIOz/QVahRII3ZZMG9tGX/BtiuEl+QkLxbjHBH9+V70XG7zj2jZKeUNuce5E/3v5JT1hCy9klsvkY6XiyXmWBEqh0GgjUTDiVoWm0pD7XA0c=
