language: ruby
sudo: false
rvm:
- '2.2.3'
- '2.2.4'
- '2.2.5'
- '2.3.0'
- '2.3.1'
- '2.4.0'
- '2.4.1'
- '2.4.2'
- ruby-head
script:
- bundle install
- ruby -I test ./test/test_soda.rb
matrix:
  allow_failures:
  - rvm: ruby-head
notifications:
  slack:
    secure: bsPzMlTJZRJEvt16O8RdP/YeXA/TwbdPiGlRgNJXPn1vL4WU/uNBLBAG8JqCybLLIOz/QVahRII3ZZMG9tGX/BtiuEl+QkLxbjHBH9+V70XG7zj2jZKeUNuce5E/3v5JT1hCy9klsvkY6XiyXmWBEqh0GgjUTDiVoWm0pD7XA0c=
